import Head from 'next/head'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home({ clients }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <header className={styles.header}>
          <h1>E-Commerce</h1>
        </header>
        <Navbar />
        {
          clients.map(client =>
            <div key={client.id}>
              <h4>{client.name + " " + client.lastName}</h4>
              <small>{client.email}</small>
            </div>
          )
        }
      </main>
    </div>
  )
}

export async function getServerSideProps () {
  const response = await fetch('http://localhost:8080/api/clients')
  const clients = await response.json()
  console.log(clients)
  return {
    props: {
      clients
    }
  }
}